# For documentation, equivalent to the imperative command:
# kubectl expose pod nginx-pod --type=NodePort --port=80

# For migrate from imperative into declarative
# kubectl expose pod nginx-pod --type=NodePort --port=80 --dry-run=client -o yam

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx

