name: key-value-app
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - .env.database-key-value
    environment:
      - MONGODB_HOST=db
      - PORT=3000
    depends_on:
      - db
    develop:
      watch: 
        - action: sync
          path: ./backend/src
          target: /app/src 
    networks:
      - key-value-net
  db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    ports:
      - 27017:27017
    env_file:
      - .env.database-root-creds
      - .env.database-key-value
    volumes:
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
      - type: volume
        source: mongodb-data
        target: /data/db
    networks:
      - key-value-net

volumes:
  mongodb-data:

networks:
  key-value-net: