apiVersion: v1
kind: Service
metadata:
  name: my-external-svc
spec:
  type: ExternalName
  externalName: google.com
  selector:
    app: color-api
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
