# Usa una imagen base de Node.js
FROM node:22-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia solo package.json y package-lock.json primero para aprovechar la caché
COPY package*.json ./
RUN npm ci

# Copia el resto del código
COPY . . 

# Establece permisos correctos para evitar problemas de escritura
RUN chown -R node:node /app
USER node

# Expone el puerto de Vite
EXPOSE 5173

# Ejecuta Vite en modo desarrollo
CMD ["npm", "run", "dev"]
