# docker build -t key-value-backend -f Dockerfile.dev .
# docker run -d --name backend --network key-value-net -p 3000:3000  key-value-backend

FROM node:22-alpine

WORKDIR /app

COPY package*.json .

RUN npm ci

COPY . .

CMD ["npm", "run", "dev"]